apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\DAHLIA LUMBANTORUAN\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f ..\next-todo-list\docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: app-srv
  name: app-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app-srv
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\DAHLIA LUMBANTORUAN\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f ..\next-todo-list\docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/next-todo-list-default: 'true'
        io.kompose.service: app-srv
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: db_todo
            - name: MYSQL_HOST_IP
              value: mysql-srv
            - name: MYSQL_PORT
              value: '3307'
            - name: MYSQL_PASSWORD
              value: root
            - name: MYSQL_USER
              value: root
          image: localhost:5000/next-todo-list
          name: app-srv
          ports:
            - containerPort: 3003
              hostPort: 3030
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
