apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\DAHLIA LUMBANTORUAN\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f ..\next-todo-list\docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: mysql-srv
  name: mysql-srv
spec:
  ports:
    - name: '3307'
      port: 3307
      targetPort: 3306
  selector:
    io.kompose.service: mysql-srv
status:
  loadBalancer: {}
