apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\DAHLIA LUMBANTORUAN\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f ..\next-todo-list\docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: phpmyadmin-srv
  name: phpmyadmin-srv
spec:
  ports:
    - name: '80'
      port: 80
      targetPort: 80
  selector:
    io.kompose.service: phpmyadmin-srv
status:
  loadBalancer: {}
