apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\DAHLIA LUMBANTORUAN\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f ..\next-todo-list\docker-compose.yaml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: phpmyadmin-srv
  name: phpmyadmin-srv
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: phpmyadmin-srv
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\DAHLIA LUMBANTORUAN\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f ..\next-todo-list\docker-compose.yaml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/next-todo-list-default: 'true'
        io.kompose.service: phpmyadmin-srv
    spec:
      containers:
        - env:
            - name: PMA_HOST
              value: mysql-srv
            - name: PMA_PORT
              value: '3307'
          image: phpmyadmin/phpmyadmin
          name: phpadmin-ctr
          ports:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
